name: Feature request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    id: use-case
    attributes:
      label: What are you trying to achieve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution (optional)
